export const SET_TITLE_SEARCH = 'SET_TITLE_SEARCH';
export const SET_GENRES_FILTER = 'SET_GENRES_FILTER';
export const SET_SORT_FIELD = 'SET_SORT_FIELD';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const SET_RESULTS_PER_PAGE ='SET_RESULTS_PER_PAGE';
